export interface TrainingData {
  id: number;
  title: string;
  label: string;
  duration: string;
  status: string;
  type: string;
  thumbnail: string;
  avatar?: string;
}

const pdfIcon = '/images/task/pdf.png';

export const trainings: TrainingData[] = [
  {
    id: 1,
    title: "Training Name",
    label: "Basic",
    duration: "04:05:01",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
    avatar: "/images/avatar1.jpg",
  },
  {
    id: 2,
    title: "Training Name",
    label: "Basic",
    duration: "03:10:15",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 3,
    title: "Training Name",
    label: "Basic",
    duration: "05:20:30",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 4,
    title: "Training Name",
    label: "Basic",
    duration: "02:15:45",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 5,
    title: "Training Name",
    label: "Basic",
    duration: "06:00:00",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 6,
    title: "Training Name",
    label: "Basic",
    duration: "04:30:20",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 7,
    title: "Training Name",
    label: "Basic",
    duration: "03:45:10",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 8,
    title: "Training Name",
    label: "Basic",
    duration: "05:15:25",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 9,
    title: "Intermediate Training Video 1",
    label: "Intermediate",
    duration: "04:05:01",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 10,
    title: "Intermediate Training Video 2",
    label: "Intermediate",
    duration: "03:10:15",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 11,
    title: "Intermediate Training Video 3",
    label: "Intermediate",
    duration: "05:20:30",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 12,
    title: "Intermediate Training Video 4",
    label: "Intermediate",
    duration: "02:15:45",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 13,
    title: "Intermediate Training Video 5",
    label: "Intermediate",
    duration: "04:30:20",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 14,
    title: "Intermediate Training Video 6",
    label: "Intermediate",
    duration: "03:45:10",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 15,
    title: "Advance Training Video 1",
    label: "Advance",
    duration: "04:05:01",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 16,
    title: "Advance Training Video 2",
    label: "Advance",
    duration: "03:10:15",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 17,
    title: "Advance Training Video 3",
    label: "Advance",
    duration: "05:20:30",
    status: "Completed",
    type: "video",
    thumbnail: "/images/thumbnail1.jpg",
  },
  {
    id: 18,
    title: "Advance Training Video 4",
    label: "Advance",
    duration: "04:30:20",
    status: "In Progress",
    type: "video",
    thumbnail: "/images/thumbnail2.jpg",
  },
  {
    id: 19,
    title: "Advance Training PDF",
    label: "Advance",
    duration: "00:00:00",
    status: "PDF",
    type: "pdf",
    thumbnail: pdfIcon,
  },
];